### Importing Data

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("D:/Salaries.csv")
df

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148649,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,NaN
148650,148651,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148651,148652,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148652,148653,Not provided,Not provided,NaN,NaN,NaN,NaN,0.00,0.00,2014,NaN,San Francisco,NaN
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [4]:
df.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB

### What is the average BasePay?

In [6]:
df['BasePay'].mean()

66325.4488404877

### What is the highest amount of OvertimePay in the dataset?

In [7]:
df['OvertimePay'].max()

245131.88

###  What is the job title of JOSEPH DRISCOLL?

In [8]:
Result = df[df['EmployeeName'] == 'JOSEPH DRISCOLL']
Result['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

### How much does JOSEPH DRISCOLL make (including benefits)?

In [9]:
Result = df[df['EmployeeName'] == 'JOSEPH DRISCOLL']
Result['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

### What is the name of highest paid person (including benefits)?

In [10]:
Highest_Paid = df[df['TotalPayBenefits'] == df['TotalPayBenefits'].max()]
Highest_Paid

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

In [11]:
Highest_Paid['TotalPayBenefits']

0    567595.43
Name: TotalPayBenefits, dtype: float64

### What is the name of lowest paid person (including benefits)?

In [12]:
Lowest_Paid = df[df['TotalPayBenefits'] == df['TotalPayBenefits'].min()]
Lowest_Paid

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

In [13]:
Lowest_Paid['TotalPayBenefits']

148653   -618.13
Name: TotalPayBenefits, dtype: float64

### What was the average (mean) BasePay of all employees per year (2011-2014)?

In [14]:
Avg_Per_Year = df.groupby('Year')['BasePay'].mean()
Avg_Per_Year

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

###  How many unique job titles are there?

In [15]:
df['JobTitle'].nunique()

2159

###  What are the top 5 most common jobs?

In [24]:
df['JobTitle'].value_counts().head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

### How many Job Titles were represented by only one person in 2013?

In [27]:
df_2013 = df[df['Year'] == 2013]
df_2013.sort_values('Id').head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
72925,72926,Gregory P Suhr,Chief of Police,319275.01,0.00,20007.06,86533.21,339282.07,425815.28,2013,NaN,San Francisco,NaN
72926,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.00,23236.00,85431.39,336922.01,422353.40,2013,NaN,San Francisco,NaN
72927,72928,Samson Lai,"Battalion Chief, Fire Suppress",186236.42,131217.63,29648.27,57064.95,347102.32,404167.27,2013,NaN,San Francisco,NaN
72928,72929,Ellen G Moffatt,Asst Med Examiner,272855.51,23727.91,38954.54,66198.92,335537.96,401736.88,2013,NaN,San Francisco,NaN
72929,72930,Robert L Shaw,"Dep Dir for Investments, Ret",315572.01,0.00,0.00,82849.66,315572.01,398421.67,2013,NaN,San Francisco,NaN

In [28]:
Counts = df_2013['JobTitle'].value_counts()
Result = (Counts == 1).sum()
Result

202

### How many people have the word Chief in their job title?

In [30]:
Chief_JobTitle = df[df['JobTitle'].str.contains('Chief', case = False, na = False)]
Counts = Chief_JobTitle['JobTitle'].count()
Counts

627

### Is there a correlation between length of the Job Title string and Salary?

In [32]:
df['TitleLength'] = df['JobTitle'].str.len()
df['TitleLength']

0         46
1         31
2         31
3         36
4         44
          ..
148649     9
148650    12
148651    12
148652    12
148653    26
Name: TitleLength, Length: 148654, dtype: int64

In [33]:
Correlation = df['TitleLength'].corr(df['TotalPayBenefits'])
Correlation

-0.03687844593260676

In [36]:
data = df[['TitleLength','TotalPayBenefits']]
data.corr()

                  TitleLength  TotalPayBenefits
TitleLength          1.000000         -0.036878
TotalPayBenefits    -0.036878          1.000000